version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  pgadmin_data: {}

services:
  db:
    build:
      context: ../.
      dockerfile: ./docker-compose/Dockerfile
    image: local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.postgres
    ports:
      - "6543:5432"
    restart: always

  web:
    build:
      context: ../  # Root of your Django project
      dockerfile: ./docker-compose/Dockerfile.django  # You'll need this Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.postgres
    depends_on:
      - db
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
